
load('E:\antibody_dynamics\epitope_competition\figure6\batch_results_vaccine_variant\primary_inactivated_dose_1e+10.mat') %% change it into the corresponding location of primary_inactivated_dose_1e+10.mat
primarySim.t = t_vac;
primarySim.y = y_vac;
primarySim.p = p_vac;

elisaTimeGrid = 0:10:max(t_vac);

primaryElisa = compute_elisa_signal_two_epitopes_primary( ...
    primarySim, ...
    elisaTimeGrid, ...
    'Primary infection');

save('vaccination_elisa_neutralizing_vs_nonneutralizing.mat', ...
    'primaryElisa', ...
    'elisaTimeGrid');
plot_primary_infection_elisa_neu_vs_nonNeu( ...
    primaryElisa, ...
    'primary_infection_elisa_neutralizing_vs_nonneutralizing');