function plot_primary_infection_elisa_neu_vs_nonNeu_new( ...
    primaryElisa, SecondaryElisa, outPrefix)
% Compare primary and secondary ELISA responses using absolute values.
%
% Panel a: neutralizing / RBD-specific antibody response
% Panel b: non-neutralizing / non-RBD-specific antibody response
%
% Solid line : Primary infection
% Dashed line: Secondary infection
%
% Blue  : IgM
% Red   : IgG
% Black : IgM + IgG

if nargin < 3 || isempty(outPrefix)
    outPrefix = 'primary_vs_secondary_elisa_absolute_comparison';
end

%% ------------------------------------------------------------------------
% Extract absolute ELISA signals: NO log10 transformation
% -------------------------------------------------------------------------

% Primary infection
tPrimary = primaryElisa.time(:);

primaryNeuIgM   = primaryElisa.neu.IgM(:);
primaryNeuIgG   = primaryElisa.neu.IgG(:);
primaryNeuTotal = primaryElisa.neu.total(:);

primaryNonIgM   = primaryElisa.nonNeu.IgM(:);
primaryNonIgG   = primaryElisa.nonNeu.IgG(:);
primaryNonTotal = primaryElisa.nonNeu.total(:);

% Secondary infection
tSecondary = SecondaryElisa.time(:);

secondaryNeuIgM   = SecondaryElisa.neu.IgM(:);
secondaryNeuIgG   = SecondaryElisa.neu.IgG(:);
secondaryNeuTotal = SecondaryElisa.neu.total(:);

secondaryNonIgM   = SecondaryElisa.nonNeu.IgM(:);
secondaryNonIgG   = SecondaryElisa.nonNeu.IgG(:);
secondaryNonTotal = SecondaryElisa.nonNeu.total(:);

% Safety cleaning: prevent NaN/Inf or numerical negative values
allSignals = { ...
    'primaryNeuIgM', 'primaryNeuIgG', 'primaryNeuTotal', ...
    'primaryNonIgM', 'primaryNonIgG', 'primaryNonTotal', ...
    'secondaryNeuIgM', 'secondaryNeuIgG', 'secondaryNeuTotal', ...
    'secondaryNonIgM', 'secondaryNonIgG', 'secondaryNonIgM'};

for k = 1:numel(allSignals)
    eval(sprintf('%s(~isfinite(%s)) = 0;', allSignals{k}, allSignals{k}));
    eval(sprintf('%s(%s < 0) = 0;', allSignals{k}, allSignals{k}));
end

%% ------------------------------------------------------------------------
% Plot style
% -------------------------------------------------------------------------

set(groot, 'DefaultAxesFontName', 'Arial');
set(groot, 'DefaultTextFontName', 'Arial');
set(groot, 'DefaultAxesFontSize', 8.5);
set(groot, 'DefaultAxesLineWidth', 0.9);
set(groot, 'DefaultAxesTickDir', 'out');

igmColor   = [0.10 0.37 0.71]; % Blue
iggColor   = [0.80 0.18 0.16]; % Red
totalColor = [0.10 0.10 0.10]; % Black

% The shaded region denotes the interval between IgM and IgG.
primaryNeuFillColor   = [0.72 0.84 1.00];
secondaryNeuFillColor = [0.38 0.66 0.95];

primaryNonFillColor   = [1.00 0.83 0.72];
secondaryNonFillColor = [0.96 0.55 0.38];

%% ------------------------------------------------------------------------
% Use one common y-axis range for direct absolute-value comparison
% -------------------------------------------------------------------------

allY = [ ...
    primaryNeuIgM; primaryNeuIgG; primaryNeuTotal; ...
    primaryNonIgM; primaryNonIgG; primaryNonTotal; ...
    secondaryNeuIgM; secondaryNeuIgG; secondaryNeuTotal; ...
    secondaryNonIgM; secondaryNonIgG; secondaryNonTotal];

yMax = max(allY);

if isempty(yMax) || ~isfinite(yMax) || yMax <= 0
    yl = [0, 1];
else
    yl = [0, 1.08 * yMax];
end

xMax = max([tPrimary; tSecondary]);

%% ------------------------------------------------------------------------
% Create one 2 x 1 comparison figure
% -------------------------------------------------------------------------

fig = figure( ...
    'Color', 'w', ...
    'Units', 'centimeters', ...
    'Position', [2, 2, 18, 15], ...
    'Renderer', 'painters');

tl = tiledlayout(fig, 2, 1, ...
    'TileSpacing', 'compact', ...
    'Padding', 'compact');

%% ------------------------------------------------------------------------
% Panel a: Neutralizing antibodies (RBD-specific)
% -------------------------------------------------------------------------

ax1 = nexttile(tl, 1);
hold(ax1, 'on');

% Primary: solid curves
plot_response_band(ax1, ...
    tPrimary, primaryNeuIgM, primaryNeuIgG, ...
    primaryNeuFillColor, 0.22);

hP_IgM = plot(ax1, tPrimary, primaryNeuIgM, ...
    'Color', igmColor, ...
    'LineStyle', '-', ...
    'LineWidth', 1.9);

hP_IgG = plot(ax1, tPrimary, primaryNeuIgG, ...
    'Color', iggColor, ...
    'LineStyle', '-', ...
    'LineWidth', 1.9);

hP_Total = plot(ax1, tPrimary, primaryNeuTotal, ...
    'Color', totalColor, ...
    'LineStyle', '-', ...
    'LineWidth', 2.4);

% Secondary: dashed curves
plot_response_band(ax1, ...
    tSecondary, secondaryNeuIgM, secondaryNeuIgG, ...
    secondaryNeuFillColor, 0.16);

hS_IgM = plot(ax1, tSecondary, secondaryNeuIgM, ...
    'Color', igmColor, ...
    'LineStyle', '--', ...
    'LineWidth', 1.9);

hS_IgG = plot(ax1, tSecondary, secondaryNeuIgG, ...
    'Color', iggColor, ...
    'LineStyle', '--', ...
    'LineWidth', 1.9);

hS_Total = plot(ax1, tSecondary, secondaryNeuTotal, ...
    'Color', totalColor, ...
    'LineStyle', '--', ...
    'LineWidth', 2.4);

format_elisa_axes(ax1);
xlim(ax1, [0, xMax]);
ylim(ax1, yl);

ylabel(ax1, 'ELISA signal', ...
    'FontSize', 9.5, ...
    'FontWeight', 'bold');

title(ax1, 'a  Neutralizing antibody response', ...
    'FontSize', 10.5, ...
    'FontWeight', 'bold');

text(ax1, 0.02, 0.91, 'RBD-specific', ...
    'Units', 'normalized', ...
    'FontSize', 9, ...
    'FontWeight', 'bold', ...
    'Color', [0.08 0.25 0.55]);

legend(ax1, ...
    [hP_IgM, hP_IgG, hP_Total, hS_IgM, hS_IgG, hS_Total], ...
    {'Primary IgM', 'Primary IgG', 'Primary IgM + IgG', ...
     'Secondary IgM', 'Secondary IgG', 'Secondary IgM + IgG'}, ...
    'Location', 'southeast', ...
    'Box', 'off', ...
    'FontSize', 7.3, ...
    'NumColumns', 2);

hold(ax1, 'off');

%% ------------------------------------------------------------------------
% Panel b: Non-neutralizing antibodies (non-RBD-specific)
% -------------------------------------------------------------------------

ax2 = nexttile(tl, 2);
hold(ax2, 'on');

% Primary: solid curves
plot_response_band(ax2, ...
    tPrimary, primaryNonIgM, primaryNonIgG, ...
    primaryNonFillColor, 0.22);

plot(ax2, tPrimary, primaryNonIgM, ...
    'Color', igmColor, ...
    'LineStyle', '-', ...
    'LineWidth', 1.9);

plot(ax2, tPrimary, primaryNonIgG, ...
    'Color', iggColor, ...
    'LineStyle', '-', ...
    'LineWidth', 1.9);

plot(ax2, tPrimary, primaryNonTotal, ...
    'Color', totalColor, ...
    'LineStyle', '-', ...
    'LineWidth', 2.4);

% Secondary: dashed curves
plot_response_band(ax2, ...
    tSecondary, secondaryNonIgM, secondaryNonIgG, ...
    secondaryNonFillColor, 0.16);

plot(ax2, tSecondary, secondaryNonIgM, ...
    'Color', igmColor, ...
    'LineStyle', '--', ...
    'LineWidth', 1.9);

plot(ax2, tSecondary, secondaryNonIgG, ...
    'Color', iggColor, ...
    'LineStyle', '--', ...
    'LineWidth', 1.9);

plot(ax2, tSecondary, secondaryNonTotal, ...
    'Color', totalColor, ...
    'LineStyle', '--', ...
    'LineWidth', 2.4);

format_elisa_axes(ax2);
xlim(ax2, [0, xMax]);
ylim(ax2, yl);

xlabel(ax2, 'Time after infection', ...
    'FontSize', 9.5, ...
    'FontWeight', 'bold');

ylabel(ax2, 'ELISA signal', ...
    'FontSize', 9.5, ...
    'FontWeight', 'bold');

title(ax2, 'b  Non-neutralizing antibody response', ...
    'FontSize', 10.5, ...
    'FontWeight', 'bold');

text(ax2, 0.02, 0.91, 'non-RBD-specific', ...
    'Units', 'normalized', ...
    'FontSize', 9, ...
    'FontWeight', 'bold', ...
    'Color', [0.58 0.20 0.08]);

hold(ax2, 'off');

%% ------------------------------------------------------------------------
% Figure title and export
% -------------------------------------------------------------------------

title(tl, ...
    {'Comparison of primary and secondary infection ELISA responses', ...
     'Absolute ELISA signals; solid lines: primary, dashed lines: secondary'}, ...
    'FontSize', 12, ...
    'FontWeight', 'bold');

drawnow;

exportgraphics(fig, [outPrefix '.png'], ...
    'Resolution', 600, ...
    'BackgroundColor', 'white');

exportgraphics(fig, [outPrefix '.pdf'], ...
    'ContentType', 'vector', ...
    'BackgroundColor', 'white');

savefig(fig, [outPrefix '.fig']);

end

%% =========================================================================
% Draw the shaded interval between IgM and IgG
% ==========================================================================
function plot_response_band(ax, t, y1, y2, fillColor, faceAlpha)

lowerY = min(y1, y2);
upperY = max(y1, y2);

patch(ax, ...
    [t; flipud(t)], ...
    [lowerY; flipud(upperY)], ...
    fillColor, ...
    'EdgeColor', 'none', ...
    'FaceAlpha', faceAlpha, ...
    'HandleVisibility', 'off');

end

%% =========================================================================
% Nature-like axes formatting
% ==========================================================================
function format_elisa_axes(ax)

box(ax, 'off');
grid(ax, 'on');

set(ax, ...
    'FontName', 'Arial', ...
    'FontSize', 8.5, ...
    'LineWidth', 0.9, ...
    'TickDir', 'out', ...
    'Layer', 'top', ...
    'GridColor', [0.86 0.86 0.86], ...
    'GridAlpha', 0.35, ...
    'XColor', [0.15 0.15 0.15], ...
    'YColor', [0.15 0.15 0.15]);

end